### ISSUE TITLE
background on the image. 

### ISSUE THREAD

**Issue by henrikhjelm** [tgcowell/waves#1]
how to install background or fix that ?

**Comment by tgcowell** [comment]
Hi @henrikhjelm 

Apologies I'm not sure I understand the issue? 

Could you give me some more context?

Thanks

**Comment by henrikhjelm** [comment]
i dident insert the : https://fonts.googleapis.com/css2?family=Oxygen&family=Ubuntu:wght@300&display=swap 
to get the background and font packs. i did only klick on install and get the theme :)

**Comment by tgcowell** [comment]
Awesome, not a problem enjoy.
