### ISSUE TITLE
White background on select options - Maybe due to HA change? 

### ISSUE THREAD

**Issue by Danny2100** [tgcowell/waves#12]
There are white boxes on the trigger type, condition type, and action type for example in automations and scripts for action type. I think I saw some other areas I can't recall that may have been white as well presumably due to a change that the theme has not adjusted for yet. Not sure if anyone else noticed.

**Comment by Brazier85** [comment]
+1 same problem here but only in the white version.

**Comment by tgcowell** [comment]
Sorry I don't know how I missed this, I have just noticed the boxes. They actually seem to appear in the default theme, so I might not be able to change them. Will have a play around and see if there's an option.

**Comment by tgcowell** [comment]
Hi All,

I've had a quick look and while I can see and understand what you're referring too, it seems every 'theme' I have installed does the exact same thing. 

I'm not sure there is an actual 'option' to theme this part, while I will keep this open I'll keep digging and see if anyone else there is able to resolve the issue? 

Thanks

**Comment by tgcowell** [comment]
I believe I have resolved this issue today with the 2.2.0 update. apologies this has taken sometime to resolve.
