### ISSUE TITLE
 Can I get a code for this?

### ISSUE THREAD

**Issue by LUBANG37** [tgcowell/waves#13]
Can I get a code for this?
![image](https://user-images.githubusercontent.com/26896616/151155098-05f2b939-ea7f-443a-8c88-4cd75385d82c.JPG)

**Comment by tgcowell** [comment]
Hi @LUBANG37 it's just an HACS card... I don't use it anymore. but let me find it's details and i'll link it for you.

**Comment by r3mcos3** [comment]
Hi @LUBANG37 

i think is this card 
[https://github.com/nervetattoo/banner-card](url)

**Comment by LUBANG37** [comment]
> Hi @LUBANG37
> 
> i think it is this card [https://github.com/nervetattoo/banner-card](url)

Thank you!!! It is beautiful :)

**Comment by tgcowell** [comment]
Thank you @r3mcos3
