### ISSUE TITLE
missing background image

### ISSUE THREAD

**Issue by rhgiter** [tgcowell/waves#15]
after latest update i am missing background image

**Comment by tgcowell** [comment]
Hi @rhgiter 

Strange, the updated didn't change the background location etc. so I'm not sure how/what has happened here... maybe you could try removing the theme and re-installing it? I'd also suggest a reboot of HA and clear browser cache?

I can't see anything suggesting it's not working. But I will keep digging around.

**Comment by rhgiter** [comment]
same for problem on 2 different pc and my phone

reinstall and cleared cache

**Comment by tgcowell** [comment]
Curious can you roll back in HACS to the previous version? 

Click on redownload and then from the dropdown select the version before. And confirm if you have the issue.

**Comment by rhgiter** [comment]
hmmm version 2.10  - same problem. :-/

HA is up to date, maybe it changed something ?

**Comment by tgcowell** [comment]
Ok, so I'm guessing there is a bad reference somewhere within your HA. The theme refers to hacsfiles/themes etc etc so if this isn't available it will create errors.

**Comment by masterfixedit** [comment]
Hi, i have the same problem. Had no previous installation of the theme.
Maybe it has something to do with following line in configuration.yaml?
`frontend:
  themes: !include_dir_merge_named themes`

I edited your yaml file so that it points to another location where files are stored but it doesn't help at all.
`/config/themes/wavesbackground.png`

**Comment by rhgiter** [comment]
i got it to work - in my lovelace yaml - i changed background: var(--background-image)  to  this

lovelace-background: var(--background-image)

**Comment by masterfixedit** [comment]
> 

I added `lovelace-background: var(--background-image)` to my lovelace.yaml and now the problem is also solved for me 😃 
Thanx!

**Comment by victorcpascua** [comment]
Same problem here  (V.2.2.0), but actually showing in phone, but not in desktop (refreshed cache, tested in incognito, tested in other browser).

(I modified the yaml to point to another location, for test, and same results)

**Comment by tgcowell** [comment]
add to your .yaml should resolve issue.
