### ISSUE TITLE
Improve inputs visibility

### ISSUE THREAD

**Issue by victorcpascua** [tgcowell/waves#17]
The inputs can only been visibles when 'hover' them, i reacon it will have more readability without this.

![image](https://user-images.githubusercontent.com/39152749/160908848-2452479a-bca7-49bf-92bb-d2aaec1fede4.png)

![image](https://user-images.githubusercontent.com/39152749/160908874-efd5762b-a539-4e00-a330-983d7defa921.png)

(Sorry for my bad English)

**Comment by tgcowell** [comment]
Understood you can adjust this yourself, however this is my preference.
