### ISSUE TITLE
Font Color in Search fields

### ISSUE THREAD

**Issue by snp88** [tgcowell/waves#19]
Hi :) 
First thx for your theme it is awesome ;)

i have one thing to add 
Font color in search fields.
Right now it is less readable in my opinion.
Should this be a the same as other fonts color ?
![image](https://user-images.githubusercontent.com/46537540/162911367-bfcb2c83-3260-4210-9489-26aa5c517f89.png)

**Comment by tgcowell** [comment]
Hi There,

I honestly am not sure what has happened but I fixed this in a release that has somehow vanished. The same issue has occurred with other themes I've had installed. I am working on it as we speak.

Cheers

**Comment by tgcowell** [comment]
download and install v2.2.0

**Comment by bjornsivertsen** [comment]
Confirmed that everything is working!
