### ISSUE TITLE
color bug ? 

### ISSUE THREAD

**Issue by henrikhjelm** [tgcowell/waves#2]
![Screenshot (1)](https://user-images.githubusercontent.com/5031424/127797311-8bb24d00-6a90-40d4-96fa-7174fb30e9f6.png)

**Comment by tgcowell** [comment]
Hi There,

Sorry could you give me more information? What part of this do you not like etc? Happy to help try and fix your concern just need alittle more information to work with.

Thanks

**Comment by henrikhjelm** [comment]
activate (aktivera)
it feels like it is to light of a color. hard to read the text

**Comment by tgcowell** [comment]
Hi @henrikhjelm,

Let me have a play around with this... themes have a strict set of variables that affect the feel. If I change this particular one it will actually change the colors throughout the entire theme. 

I'll see what I can do to make it appear easier to read

**Comment by tgcowell** [comment]
I have made a minor change to the primary-color making it a slightly brighter blue, hopefully this is now easier to read?

**Comment by henrikhjelm** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/5031424/128015264-dc239b20-5859-4be7-a552-cfd356dc3db5.png)
it is a bit better now :)

**Comment by tgcowell** [comment]
Hi @henrikhjelm 

Great, I'll keep an eye on the feedback and if people want it changed I'm happy to play with it a little more... only the brighter it gets or vivid it starts to impact on the overall feel. 

Thanks
