### ISSUE TITLE
Theme automation

### ISSUE THREAD

**Issue by jcamm3** [tgcowell/waves#20]
I run 5 HA instances.  All are running 'waves' along with the automation to change themes for daytime and nighttime use.  2 of the 5 units are no longer changing themes based on the automation tasks.  I can, however, manually change themes through manual user profile selections.  Is anyone seeing similar behavior?

Host Operating System | Home Assistant OS 8.0
Supervisor Version | supervisor-2022.05.2

**Comment by tgcowell** [comment]
Hi @jcamm3 

This sounds like more of a configuration issue over an actual fault within the theme itself, I'd have a look at the automation and see if there is anything obvious. 

Step through the automation and see if the logs can point you to why its failing (debug) as you state 3 of your instances are working so perhaps refer to them.

Cheers
