### ISSUE TITLE
Automation/Script Editor Bug

### ISSUE THREAD

**Issue by Danny2100** [tgcowell/waves#22]
I thought this issue was a front end issue until I switched over to the mushroom theme and noticed it might be a waves issue.

This is on android 12.

See mushroom pictures.
![Screenshot_20220617-081526_Home Assistant](https://user-images.githubusercontent.com/47092714/174296367-e3f322ec-27b0-4050-851d-cdd136e79dda.jpg)
![Screenshot_20220617-081519_Home Assistant](https://user-images.githubusercontent.com/47092714/174296368-0e9a43bd-f310-4bdf-a2c1-f659d41b524b.jpg)
![Screenshot_20220617-081513_Home Assistant](https://user-images.githubusercontent.com/47092714/174296370-4419d89d-1d48-42f0-9971-acbb5f6e23a8.jpg)

For waves pictures see the issue I created in frontend. 

[Front End Issue ](https://github.com/home-assistant/frontend/issues/12347)

**Comment by tgcowell** [comment]
Hi @Danny2100 

Does this also occur in browser? I don't have an Android phone and am unable to re-produce the issues on an iPhone.

![image](https://user-images.githubusercontent.com/6628530/174414283-0e4c13c6-4b3a-4b21-ac20-d7be537104c0.jpeg)

![image](https://user-images.githubusercontent.com/6628530/174414296-b2232c07-5d03-4cd1-8c60-d72ef10a8a73.png)

![image](https://user-images.githubusercontent.com/6628530/174414303-aad27564-db0c-4f5e-8f42-5eccae67c32e.png)

![image](https://user-images.githubusercontent.com/6628530/174414306-18c1dd03-ee6f-4852-9664-bf3d2388d556.png)

![image](https://user-images.githubusercontent.com/6628530/174414308-46533b83-e90e-465c-818e-d1c8cabe8335.png)

I'll have a look around and see if there is anything else that I can see, I did have a similar issue with the "white" which I resolved. However GitHub keeps reverting back to a previous release.
