### ISSUE TITLE
Possible to change total width of the cards in lovelace UI?

### ISSUE THREAD

**Issue by deeeblack** [tgcowell/waves#23]
Hi mate, Just want to say that the theme is great. Appreciate your work on it.

Is there an easy way to open up the total width of the cards in the lovelace? or did you make it that narrow to suit mobile view?or am I missing something?

Thanks

![width](https://user-images.githubusercontent.com/18100269/178114886-aaa7480f-f2a5-47a3-a707-720c17030376.JPG)

**Comment by deeeblack** [comment]
Disregard! I think i got it sorted! sorry, still learning!

**Comment by tgcowell** [comment]
Hi @deeeblack 

It's a fixed parameter based on HA cards. There are LOTS of options within HACS that allow you to further customise the overall look and feel.

I actually moved away from the traditional theme and HA cards and am now using 

UI Minimalist, if you're ok with yaml then I recommend. If you're not comfortable with yaml then have a look at Mushroom cards they're available via the HA UI and look/feel the same.

![image](https://user-images.githubusercontent.com/6628530/178126476-2210b496-081f-47ce-ad29-3150c9b9059b.jpeg)

**Comment by deeeblack** [comment]
Yea I have been playing with mushroom cards.

 

This shit is addictive!!!

 



 

I’ll get into it! Again thanks! Appreciate the response.
