### ISSUE TITLE
V2.30. Won't let me select light/dark waves theme in cards or lovelace view configuration

### ISSUE THREAD

**Issue by escobarin3** [tgcowell/waves#27]
I had several cards and some lovelace views configured with dark-waves... (independent if I use dark or light theme)... now there is no option available, only "waves"

![image](https://user-images.githubusercontent.com/85810778/181104470-0ef74a3d-fe06-4703-8d04-7fbe03c179ea.png)

**Comment by tgcowell** [comment]
Hi @escobarin3 

The theme has been updated to align with HA auto, light and dark modes.

**auto**
![image](https://user-images.githubusercontent.com/6628530/185709586-7393c519-e1fd-4754-bc0a-f05127372f63.jpeg)

**light**
![image](https://user-images.githubusercontent.com/6628530/185709611-93f66922-85d1-4379-ad34-41c865b43437.jpeg)

**dark**
![image](https://user-images.githubusercontent.com/6628530/185709671-b6092d9e-08c8-43f1-952a-c23a7c258b6c.jpeg)

So there is a single waves theme, you call that theme in your automation and select the correct light or dark mode. 

**automation**
![image](https://user-images.githubusercontent.com/6628530/185709860-84828fd7-56d3-4c20-9b7b-aed56d720e0a.jpeg)
