### ISSUE TITLE
White borders on each card

### ISSUE THREAD

**Issue by snp88** [tgcowell/waves#29]
After recent HA update (2022.11.0) all cards have white borders

this is effect of recent change in HA 
https://www.home-assistant.io/blog/2022/11/02/release-202211/
_The default dashboard theme has been adjusted to move a little closer to the new Material Design 3 guidelines. Borders around cards are now outlined (instead of having a shadow), and corners are a little more rounded.****_

Not sure is that kind of issue can be resolve by update the theme setup ;) 
But if yes that would be great

![image](https://user-images.githubusercontent.com/46537540/199687861-1f491cad-00b3-461a-af56-c0113cb2cde6.png)

**Comment by ndriu** [comment]
You can try add to waves.yaml file:

ha-card-border-width: '0px'

it should fix the problem.

BR,
Andrzej

**Comment by snp88** [comment]
> You can try add to waves.yaml file:
> 
> ha-card-border-width: '0px'
> 
> it should fix the problem.
> 
> BR, Andrzej

This work for me

**Comment by tgcowell** [comment]
Fixed
