### ISSUE TITLE
Is there any way to fix 2022.12 update color change?

### ISSUE THREAD

**Issue by brpeterso** [tgcowell/waves#32]
The latest 2022.12 update completely messed up the waves theme with terrible colors for device states.  It's not as clean as it was before.  Is this something that can be addressed in the theme, or do we have to change colors directly in our cards?  Thanks!

It looks like these are the new color states that need to be called out in the theme.  https://community.home-assistant.io/t/i-dislike-the-2022-12-color-changes/499890/164

**Comment by bboudewijns** [comment]
Wondering about the same! I love the theme, but now I have yellow icons everywhere. Any help would be greatly appreciated!

**Comment by LegendaryFire** [comment]
Experiencing the same issues.

**Comment by LegendaryFire** [comment]
@brpeterso @bboudewijns Fixed the issue, currently pending approval in the pull request I submitted. For a solution in the meantime, view the source I posted.

**Comment by bboudewijns** [comment]
Worked like a charm! Thanks a lot!

**Comment by LegendaryFire** [comment]
> Worked like a charm! Thanks a lot!

No problem, glad it was helpful!

**Comment by tgcowell** [comment]
Done

**Comment by bboudewijns** [comment]
Hello again. Unfortunately the same happened again with the 2023.2.0 update. 

Any chance for an update again? Thanks.
