### ISSUE TITLE
Create a new release so HACS updates

### ISSUE THREAD

**Issue by m1ckyb** [tgcowell/waves#35]
Hi,

Seeing if you can create a new release so can get the latest code changes in HACS.

Thanks

**Comment by tgcowell** [comment]
Hi @m1ckyb 

I will do my best today/tomorrow just on a holiday in regional Australia with limited internet

Cheers

**Comment by tgcowell** [comment]
Done

**Comment by m1ckyb** [comment]
Thanks,

Enjoy your holiday
