### ISSUE TITLE
Background not shown

### ISSUE THREAD

**Issue by loadamasta** [tgcowell/waves#41]
I am not sure if this is a theme or a HA issue. But since HA 2023.1 the backround of the theme is no longer visible. Deleting cache etc. did not solve the issue.

**Comment by gmaslowski** [comment]
Hi @loadamasta . Please refer to the installations instruction. In recent versions of HACS, all assets need to be copied manually to a different location -> https://github.com/tgcowell/waves/blob/master/README.md#backgrounds--animated-icons

**Comment by tgcowell** [comment]
As per @gmaslowski comments, please refer to updates. I'll also update the readme shortly.
