### ISSUE TITLE
Weather card don't show weather icon 

### ISSUE THREAD

**Issue by snp88** [tgcowell/waves#44]
Hi 

I some recent update weather card stop showing the icons 
Check the screenshot 
![image](https://user-images.githubusercontent.com/46537540/217308210-9457dc66-a40b-49fa-9560-a65707288377.png)

**Comment by snp88** [comment]
This is issue is only for this theme 
when i switch theme icon are present

**Comment by Arnaud-Albrecht** [comment]
I have the same problem
Found any fixes. For now i just switched themes.

**Comment by Arnaud-Albrecht** [comment]
Going into the theme folder then removing all references to animated weather icons in the wave.yaml file actually fixed it for me.
You'll have to restart your server to take effect.

**Comment by Richdem** [comment]
I really like this theme,
Hopefully the Dev can fix this issue

**Comment by tgcowell** [comment]
Hi All,

Can you please refer to the instructions and let me know if this fixes it?

HACS made changes the required a new directory as per recent update instructions.

Thanks

![image](https://user-images.githubusercontent.com/6628530/221378652-e991a012-1232-40ad-8b7a-db6545fec542.jpeg)

**Comment by Richdem** [comment]
Thank you,
I can try within the hour and will report back
Appreciate the quick response

**Comment by Richdem** [comment]
This worked perfectly,

Now my animated icons are back :)

Thank you again

**Comment by snp88** [comment]
Works for me ;)
![image](https://user-images.githubusercontent.com/46537540/221384008-543b074a-48d6-4b4e-aa7b-c2b9fa4ddef6.png)

**Comment by chanpod** [comment]
I'm also having this issue. I have put all the icons in both the 

<rootDirectory>/config/www/waves
and
<rootDirectory>/themes/config/www/waves

My icons and background are still not showing up :(
