### ISSUE TITLE
Icon State Colour

### ISSUE THREAD

**Issue by johnjoemorgan** [tgcowell/waves#5]
A request ...

Thanks for a great theme - my default now.

Would it be possible to (have the option to) change the 'on state' colour to yellow or another colour that contrasts better with the background?

Cheers

John

**Comment by tgcowell** [comment]
Hi @johnjoemorgan,

I can't do anything within the theme because they're all lockdown to certain variables. However I think there is a custom component that allows you to adjust this. Leave it with me and I'll see if I can get this setup and pass on the requirements.

You can also just open the theme .yaml file file the icon state and change to whatever colour you prefer. Just note if you update via HACS I believe it will override.

**Comment by johnjoemorgan** [comment]
Thanks @tgcowell hadn't really thought about editing themes till you prompted me here.

Changed this in waves.yaml

  #state-icon-active-color: var(--primary-color)
  state-icon-active-color: "#FFA500"

![Overview-Castel](https://user-images.githubusercontent.com/45795798/129442703-e0ef3226-608e-44aa-bb39-4c27bc6cfccf.png)

**Comment by tgcowell** [comment]
Awesome glad you liked it, I'm making a few more at the moment I like design would really really like to redo HA think it's design could really push it forward but anyway will see how we go.

**Comment by tgcowell** [comment]
Hi @johnjoemorgan 

I've played around with the colours and I'm having a hard time finding one I'm happy to build into the finished theme. I think your orange is perfect to high if an item is on/off but I personally don't like it within the theme, thoughts?

- [ ] Blue (lighter)
- [ ] Green 
- [ ] Original
- [ ] Keep my orange! 

I like Flat Colours.

I think it's a valid issue so I'll 100% adjust but let me know.

Thanks again for highlighting it!

**Comment by johnjoemorgan** [comment]
@tgcowell This is why design is such a bind sometimes!  I have shown the orange to clients and family and they prefer it.   

Away from the orange - I'd go with the green as long as the shade is high contrast against the light or dark theme

r/

John

**Comment by tgcowell** [comment]
Hi @johnjoemorgan,

I've changed to a bright blue color, if you update to the latest version v.2.0.3 you will download that update and a fix for the calendar card if you use it.

Cheers
