### ISSUE TITLE
No borders around cards since 2.0.3

### ISSUE THREAD

**Issue by RickxZen** [tgcowell/waves#7]
I noticed the borders around cards disappeared since updating to the latest release 2.0.3

In the picture below the red lines are edges of the card and they blend in with the background.

This makes the dashboard harder to read for certain areas.

![afbeelding](https://user-images.githubusercontent.com/48241736/130746137-ae1ef133-5ea8-4a3c-8d01-422a91ebf8df.png)

I will make a PR to revert this.

**Comment by tgcowell** [comment]
Resolve with v2.0.4 - 

FYI - Apologies the cards are actually there, you will notice the background image is missing here. This is what is needed in order for the cards to appear correctly.

I've fixed this (was an incorrect URL to background.png) thanks for sending it through.

Cheers
